IMPORT DEPENDENCIES

In [1]:
#!pip install stable-baselines3[extra]


In [2]:
import sys
print (sys.version)

3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]


In [3]:
import gym 
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

ENVIRONMENT

In [49]:
environment_name = "CartPole-v0"

In [50]:
env = gym.make(environment_name)

In [51]:
env.__dict__

{'env': <gym.envs.classic_control.cartpole.CartPoleEnv at 0x2134f0a0730>,
 '_action_space': None,
 '_observation_space': None,
 '_reward_range': None,
 '_metadata': None,
 '_max_episode_steps': 200,
 '_elapsed_steps': None}

In [53]:
env.close()

In [52]:
episodes = 5
for episode in range (1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, action = env.step(action)
        score += reward
    print('Episode : {}  Score : {} '.format(episode, score))
env.close()
        
    

Episode : 1  Score : 42.0 
Episode : 2  Score : 12.0 
Episode : 3  Score : 17.0 
Episode : 4  Score : 17.0 
Episode : 5  Score : 31.0 


In [8]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [9]:
env.reset()

array([0.03145589, 0.02618108, 0.04808271, 0.04402215], dtype=float32)

In [10]:
env.step(1)

(array([ 0.03197952,  0.22058176,  0.04896315, -0.23311096], dtype=float32),
 1.0,
 False,
 {})

https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

TRAIN AN RL MODEL

In [11]:
import os

In [12]:
log_path = os.path.join("Training","Logs")

In [13]:
log_path

'Training\\Logs'

In [14]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)


Using cpu device


In [15]:
PPO??

Init signature:
PPO(
    policy: Union[str, Type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gym.core.Env, stable_baselines3.common.vec_env.base_vec_env.VecEnv, str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    target_kl: Union[float, NoneType] = None,
    tensorboard_log: Union[str, NoneType] = None,
    create_eval_env: bool = False,
    policy_kwargs: Union[Dict[str, Any], NoneType] = None,
    verbose: int = 0,
    seed: Union[int, NoneType] = None,
    device: Union[torch.device, str] = 

In [16]:
model.learn(total_timesteps=20000)
#ici 20 000 ok
#pr autres problemes peut être bcp plus haut ex: voiture ~350 000

Logging to Training\Logs\PPO_7
-----------------------------
| time/              |      |
|    fps             | 191  |
|    iterations      | 1    |
|    time_elapsed    | 10   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 318         |
|    iterations           | 2           |
|    time_elapsed         | 12          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.007846857 |
|    clip_fraction        | 0.0813      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | 0.0177      |
|    learning_rate        | 0.0003      |
|    loss                 | 8.88        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0134     |
|    value_loss           | 53.3        |
-----------------------------------------
---

SAVE AND RELOAD

In [17]:
PPO_Path= os.path.join('Training','Saved Models', 'PPO_Model_CartPole')

In [18]:
model.save(PPO_Path)

In [19]:
del model

In [20]:
model=PPO.load(PPO_Path, env=env)

In [21]:
model.learn(total_timesteps=20000)

Logging to Training\Logs\PPO_8
-----------------------------
| time/              |      |
|    fps             | 1946 |
|    iterations      | 1    |
|    time_elapsed    | 1    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1448        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.005425535 |
|    clip_fraction        | 0.0226      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.544      |
|    explained_variance   | 0.737       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.796       |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00412    |
|    value_loss           | 6.46        |
-----------------------------------------
---

EVALUATION

In [22]:
evaluate_policy(model,env,n_eval_episodes=10,render=True)
#render = visualisation

C:\Users\cleger\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\stable_baselines3\common\evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(200.0, 0.0)

In [23]:
env.close()

TEST MODEL

In [24]:
episodes = 10
for episode in range (1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action, _ = model.predict(obs)
        obs, reward, done, action = env.step(action)
        score += reward
    print('Episode : {}  Score : {} '.format(episode, score))
env.close()
        
    

Episode : 1  Score : [200.] 
Episode : 2  Score : [200.] 
Episode : 3  Score : [200.] 
Episode : 4  Score : [200.] 
Episode : 5  Score : [200.] 
Episode : 6  Score : [200.] 
Episode : 7  Score : [200.] 
Episode : 8  Score : [200.] 
Episode : 9  Score : [200.] 
Episode : 10  Score : [200.] 


In [25]:
obs=env.reset()

In [26]:
model.predict(obs)
#nombre ds le tableau = action à prendre

(array([1], dtype=int64), None)

In [27]:
action, _ = model.predict(obs)

In [28]:
env.step(action)

(array([[ 0.00944601, -0.15637067, -0.01232144,  0.2609867 ]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{}])


VIEWING LOGS IN TENSERBOARD

In [29]:
training_log_path = os.path.join(log_path,"PPO_4")

In [30]:
training_log_path

'Training\\Logs\\PPO_4'

In [31]:
log_path

'Training\\Logs'

In [32]:
!tensorboard --logdir = (training_log_path)
# ! = magic command


2022-06-10 15:59:28.061878: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-06-10 15:59:28.061940: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
usage: tensorboard [-h] [--helpfull] [--logdir PATH] [--logdir_spec PATH_SPEC]
                   [--host ADDR] [--bind_all] [--port PORT]
                   [--reuse_port BOOL] [--load_fast {false,auto,true}]
                   [--extra_data_server_flags EXTRA_DATA_SERVER_FLAGS]
                   [--grpc_creds_type {local,ssl,ssl_dev}]
                   [--grpc_data_provider PORT] [--purge_orphaned_data BOOL]
                   [--db URI] [--db_import] [--inspect] [--version_tb]
                   [--tag TAG] [--event_file PATH] [--path_prefix PATH]
                   [--window_title TEXT] [--max_reload_threads COUNT]
                   [--reload_inter

ADDING A CALLBACK TO TRAINING STAGE

7. Adding a callback to the training Stage

In [33]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold
import os

In [34]:
save_path=os.path.join('Training','Saved Models')

In [35]:
save_path

'Training\\Saved Models'

In [36]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200,verbose = 1)
eval_callback= EvalCallback(env, callback_on_new_best=stop_callback, eval_freq=100000, best_model_save_path=save_path, verbose=1)

In [37]:
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device


In [38]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_9
-----------------------------
| time/              |      |
|    fps             | 2440 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1654        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008686167 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.685      |
|    explained_variance   | -0.003      |
|    learning_rate        | 0.0003      |
|    loss                 | 9.69        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0201     |
|    value_loss           | 54.7        |
-----------------------------------------
---

In [39]:
model_path = os.path.join('Training', 'Saved Models', 'best_model')


In [40]:
#model = PPO.load(model_path, env=env)


CHANGING POLICIES

In [41]:
net_arch=[dict(pi=[128, 128, 128, 128], vf=[128, 128, 128, 128])]


In [42]:
model = PPO('MlpPolicy', env, verbose = 1,policy_kwargs={'net_arch' : net_arch})

Using cpu device


In [43]:
model.learn(total_timesteps=20000, callback=eval_callback)

-----------------------------
| time/              |      |
|    fps             | 1782 |
|    iterations      | 1    |
|    time_elapsed    | 1    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1005        |
|    iterations           | 2           |
|    time_elapsed         | 4           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.013886062 |
|    clip_fraction        | 0.225       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -0.0117     |
|    learning_rate        | 0.0003      |
|    loss                 | 3.66        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0249     |
|    value_loss           | 21.5        |
-----------------------------------------
----------------------------------

In [44]:
from stable_baselines3 import DQN

In [45]:
model = DQN('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device


In [46]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\DQN_3
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.943    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 4946     |
|    time_elapsed     | 0        |
|    total_timesteps  | 119      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.909    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 5162     |
|    time_elapsed     | 0        |
|    total_timesteps  | 191      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.866    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 5640     |
|    time_elapsed     | 0        |
|    total_timesteps  | 282      |
----------------------------------
------------------------